### ISSUE TITLE
Maintaining General Health for Clients

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#11]
Below are some of the things that can be done to maintain the general health of the clients.

- [x] Add a `DEVELOPER_GUIDE` to make it easy for the community to get started with the client. Refer [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/opensearch-java/blob/main/DEVELOPER_GUIDE.md)
- [x] Add a `TESTING_GUIDE` for client development.
- [x] Follow branching standards described in https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching.
- [x] Add auto backport functionality to maintain development across multiple branches easily. Refer [BACKPORT.md] https://github.com/opensearch-project/opensearch-clients/issues/14(https://github.com/opensearch-project/opensearch-plugins/blob/main/BACKPORT.md)
- [x] Add a compatibility matrix for the client. Refer [COMPATIBILITY.md](https://github.com/opensearch-project/opensearch-java/blob/main/COMPATIBILITY.md) - #8 
- [x] Support tests running across compatible versions of OpenSearch for the current client version. - #8 
- [x] Add ability to test against developing unreleased OpenSearch to make required changes to the client. This will help in developing  and maintaining clients according to changes to OpenSearch.
- [x] Add broken link checker. Refer https://github.com/opensearch-project/opensearch-plugins/blob/main/.github/workflows/links.yml
- [x] Add CVE scanning for the client.
- [ ] Add Dependabot auto upgrade to keep the dependencies up-to-date.
- [x] Add standard issue/feature templates from .github.

**Comment by wbeckler** [comment]
These all look done to me. Any objections if we close?
