### ISSUE TITLE
[META] Add support for inclusive naming for all clients

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-clients#16]
**Is your feature request related to a problem?**
Starting with OpenSearch 2.0, we are moving to support inclusive naming across the project. 
Ref: 
[1] https://github.com/opensearch-project/OpenSearch/issues/472
cc: @tlfeng

Coming from: https://github.com/opensearch-project/opensearch-py/pull/156#discussion_r854547613

**What solution would you like?**
Add support to new inclusive REST API usages.
Change any internal REST API calls (which don't face to user) to use new inclusive usages, instead of the old REST APIs that contain "master" terminology. Otherwise, using REST API usages with "master" word will lead to deprecation warning emitted from OpenSearch server.
Additional Context:
The REST API and setting changes about "master" terminology:
https://github.com/opensearch-project/documentation-website/issues/450

The setting change about "blacklist / whitelist" terminology:
https://github.com/opensearch-project/documentation-website/issues/449

Note: The REST API parameter "master_timeout" is not deprecated in 2.0 (but in 3.0) to keep the compatibility of OpenSearch "High Level REST Client" with server version 1.x (See the issue https://github.com/opensearch-project/OpenSearch/issues/2928 for detail)

**Tracking changes in clients**

- [x] opensearch-java - https://github.com/opensearch-project/opensearch-java/issues/166
- [x] opensearch-ruby - https://github.com/opensearch-project/opensearch-ruby/issues/72
- [x] opensearch-php - https://github.com/opensearch-project/opensearch-php/issues/61
- [x] opensearch-js - https://github.com/opensearch-project/opensearch-js/issues/221
- [x] opensearch-dsl-py - https://github.com/opensearch-project/opensearch-dsl-py/issues/60
- [x] opensearch-go - https://github.com/opensearch-project/opensearch-go/issues/121
- [x] opensearch-rs - https://github.com/opensearch-project/opensearch-rs/issues/56
- [x] opensearch-py - https://github.com/opensearch-project/opensearch-py/issues/174
- [x] opensearch-net - https://github.com/opensearch-project/opensearch-net/issues/89

**Comment by tlfeng** [comment]
You could feel free to add the following to the top ^ 😁 : 

Suggested solution:
1. Add support to new inclusive REST API usages.
2. Change any internal REST API calls (which don't face to user) to use new inclusive usages, instead of the old REST APIs that contain "master" terminology. Otherwise, using REST API usages with "master" word will lead to deprecation warning emitted from OpenSearch server.

Additional Context:
The REST API and setting changes about "master" terminology:
https://github.com/opensearch-project/documentation-website/issues/450

The setting change about "blacklist / whitelist" terminology:
https://github.com/opensearch-project/documentation-website/issues/449

Note: The REST API parameter "master_timeout" is not deprecated in 2.0 (but in 3.0) to keep the compatibility of OpenSearch "High Level REST Client" with server version 1.x (See the issue https://github.com/opensearch-project/OpenSearch/issues/2928 for detail)

**Comment by saratvemulapalli** [comment]
JS: https://github.com/opensearch-project/opensearch-js/pull/224

**Comment by VachaShah** [comment]
Thank you @saratvemulapalli for opening this! Converting this into a meta issue to track the changes for various clients.

**Comment by VachaShah** [comment]
Closing this issue since all existing clients support inclusive naming.
