### ISSUE TITLE
[META] Release 2.0.0 version for clients

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#21]
This is a meta issue for tracking the release for 2.0.0 version for the clients.

- [ ] `opensearch-java` - https://github.com/opensearch-project/opensearch-java/issues/159
- [ ] `opensearch-py` - https://github.com/opensearch-project/opensearch-py/issues/166
- [ ] `opensearch-ruby` - https://github.com/opensearch-project/opensearch-ruby/issues/68
- [ ] `opensearch-js` - https://github.com/opensearch-project/opensearch-js/issues/245
- [ ] `opensearch-go` - https://github.com/opensearch-project/opensearch-go/issues/110
- [ ] `opensearch-php` - https://github.com/opensearch-project/opensearch-php/issues/56
- [ ] `opensearch-dsl-py`
- [ ] `opensearch-rs`
- [ ] `opensearch-net`

**Comment by VachaShah** [comment]
Targeted release dates for the clients:



Client | Target Release Date
-- | --
opensearch-py | 2022-05-26
opensearch-js | 2022-05-26
opensearch-go | 2022-05-26
opensearch-ruby | 2022-05-31
opensearch-java | 2022-05-31
opensearch-rs | 2022-06-01
opensearch-dsl-py | 2022-06-01

**Comment by VachaShah** [comment]
Clients released for 2.0.0:

**opensearch-go**

- https://github.com/opensearch-project/opensearch-go/releases/tag/v2.0.0

**opensearch-php**
https://packagist.org/packages/opensearch-project/opensearch-php
https://github.com/opensearch-project/opensearch-php/releases/tag/2.0.0

**opensearch-ruby**

- https://rubygems.org/gems/opensearch-ruby/versions/2.0.0
- https://rubygems.org/gems/opensearch-api/versions/2.0.0
- https://rubygems.org/gems/opensearch-transport/versions/2.0.0
- https://rubygems.org/gems/opensearch-dsl/versions/0.2.0
- https://github.com/opensearch-project/opensearch-ruby/releases/tag/v2.0.0

**opensearch-py**

- https://pypi.org/project/opensearch-py/2.0.0
- https://github.com/opensearch-project/opensearch-py/releases/tag/v2.0.0

**opensearch-java**

- https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.0.0/
- https://github.com/opensearch-project/opensearch-java/releases/tag/v2.0.0

**opensearch-js**

- https://www.npmjs.com/package/@opensearch-project/opensearch/v/2.0.0
- https://github.com/opensearch-project/opensearch-js/releases/tag/2.0.0

**opensearch-rs**

- https://crates.io/crates/opensearch/2.0.0
- https://github.com/opensearch-project/opensearch-rs/releases/tag/v2.0.0

**opensearch-dsl-py**

- https://pypi.org/project/opensearch-dsl/2.0.1/
- https://github.com/opensearch-project/opensearch-dsl-py/releases/tag/v2.0.0
