### ISSUE TITLE
[META] Add support for AWS Sigv4 request signer

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#22]
- [x] https://github.com/opensearch-project/opensearch-java/issues/55
- [x] https://github.com/opensearch-project/opensearch-ruby/issues/71
- [x] https://github.com/opensearch-project/opensearch-php/issues/59
- [x] https://github.com/opensearch-project/opensearch-js/issues/252
- [x] https://github.com/opensearch-project/opensearch-dsl-py/issues/58
- [x] https://github.com/opensearch-project/opensearch-go/issues/117
- [x] https://github.com/opensearch-project/opensearch-rs/issues/36
- [x] https://github.com/opensearch-project/opensearch-py/issues/85
- [x] https://github.com/opensearch-project/opensearch-net/issues/65
- [ ] https://github.com/opensearch-project/opensearch-clients/issues/31

**Comment by VachaShah** [comment]
Expanding the testing for OpenSearch Service is being tracked in #47.

Closing this issue since Sigv4 support is available for all clients.
