### ISSUE TITLE
[META] Stadardize, setup, report, and increase test coverage

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-clients#30]
## What kind of business use case are you trying to solve? What are your requirements?
As of the time of writing this we have at least some integration testing across all clients (except .NET), but it's unclear how much surface those tests cover. They should be hitting 100% of APIs supported. 

**What is the problem? What is preventing you from meeting the requirements?**
Lack of code coverage.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
Setup code coverage for all clients. Once reporting from CI/CD, analyze the test gap and fill it.

Tracking issues:
- [x] https://github.com/opensearch-project/opensearch-dsl-py/issues/80
- [ ] https://github.com/opensearch-project/opensearch-go/issues/157
- [ ] https://github.com/opensearch-project/opensearch-java/issues/222
- [x] https://github.com/opensearch-project/opensearch-js/issues/298
- [ ] https://github.com/opensearch-project/opensearch-net/issues/99
- [x] https://github.com/opensearch-project/opensearch-php/issues/82
- [x] https://github.com/opensearch-project/opensearch-py/issues/197
- [ ] https://github.com/opensearch-project/opensearch-ruby/issues/100
- [ ] https://github.com/opensearch-project/opensearch-rs/issues/73

**Comment by Xtansia** [comment]
Tracking issues:
- [ ] https://github.com/opensearch-project/opensearch-dsl-py/issues/80
- [ ] https://github.com/opensearch-project/opensearch-go/issues/157
- [ ] https://github.com/opensearch-project/opensearch-java/issues/222
- [ ] https://github.com/opensearch-project/opensearch-js/issues/298
- [ ] https://github.com/opensearch-project/opensearch-net/issues/99
- [ ] https://github.com/opensearch-project/opensearch-php/issues/82
- [ ] https://github.com/opensearch-project/opensearch-py/issues/197
- [ ] https://github.com/opensearch-project/opensearch-ruby/issues/100
- [ ] https://github.com/opensearch-project/opensearch-rs/issues/73

**Comment by Xtansia** [comment]
There are already some clients and other OpenSearch projects reporting coverage statistics, which are using [codecov.io](https://about.codecov.io/) as the reporting service: https://github.com/search?l=YAML&p=1&q=org%3Aopensearch-project+codecov&type=Code.
