### ISSUE TITLE
[META] Automate and document the release process for clients

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#32]
This is a meta issue tracking automation of release process for all clients

- [x] `opensearch-go` - https://github.com/opensearch-project/opensearch-go/issues/144
- [x] `opensearch-rs` - https://github.com/opensearch-project/opensearch-rs/issues/63
- [x] `opensearch-py` - https://github.com/opensearch-project/opensearch-py/issues/185
- [x] `opensearch-dsl-py` - https://github.com/opensearch-project/opensearch-dsl-py/issues/67
- [x] `opensearch-php` - https://github.com/opensearch-project/opensearch-php/issues/77
- [x] `opensearch-ruby` - https://github.com/opensearch-project/opensearch-ruby/issues/96
- [x] `opensearch-js` - https://github.com/opensearch-project/opensearch-js/issues/274
- [x] `opensearch-net` - https://github.com/opensearch-project/opensearch-net/issues/79
- [x] `opensearch-java` - https://github.com/opensearch-project/opensearch-java/issues/349

**Comment by dblock** [comment]
Done!
