### ISSUE TITLE
[META] Improve the time taken by Github Actions on pull requests

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#53]
### Is your feature request related to a problem?
Problem is as mentioned in #39.

### What solution would you like?
Improve the `integration_unreleased` workflow as done in https://github.com/opensearch-project/opensearch-dsl-py/pull/92

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
As the matrix grows for versions to test against for the clients, the Github actions on PRs take more time to run. This change helps reducing this time significantly as stated in https://github.com/opensearch-project/opensearch-dsl-py/pull/92.

**Tracking changes for all clients**

- [x] opensearch-java https://github.com/opensearch-project/opensearch-java/issues/365
- [x] opensearch-py https://github.com/opensearch-project/opensearch-py/issues/294
- [x] opensearch-ruby https://github.com/opensearch-project/opensearch-ruby/issues/144
- [x] opensearch-rs https://github.com/opensearch-project/opensearch-rs/issues/125
- [x] opensearch-js https://github.com/opensearch-project/opensearch-js/issues/387
- [x] opensearch-php https://github.com/opensearch-project/opensearch-php/issues/126
- [x] opensearch-go https://github.com/opensearch-project/opensearch-go/issues/232
- [x] opensearch-net https://github.com/opensearch-project/opensearch-net/issues/153

**Comment by shyim** [comment]
I guess it would make more sense to have one opensearch-nightly repository which builds every night the latest artifact and automatically creates a release.

So it code won't be complex inside the clients, as they just download an artifact/release/docker from there

**Comment by dblock** [comment]
@shyim you could add any nightly/cron GHA to this repo that would execute the test matrix
