### ISSUE TITLE
[META] Test clients regularly against the server

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#59]
### Is your feature request related to a problem?
Tests against unreleased OpenSearch run on each PR but there might be commits in between on OpenSearch which break the client. Similarly, the tests against Amazon OpenSearch Service and Amazon OpenSearch Serverless also need to be run on a cron basis to determine if something breaks the compatibility.

### What solution would you like?
Run the tests on a cron schedule and monitor + fix failures.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
The test setup for client testing against Amazon OpenSearch Service and Amazon OpenSearch Serverless is covered in issue #47.

## Client issue tracking

- [ ] https://github.com/opensearch-project/opensearch-java/issues/469
- [ ] https://github.com/opensearch-project/opensearch-py/issues/382
- [ ] https://github.com/opensearch-project/opensearch-ruby/issues/173
- [x] https://github.com/opensearch-project/opensearch-rs/issues/163
- [ ] https://github.com/opensearch-project/opensearch-js/issues/505
- [ ] https://github.com/opensearch-project/opensearch-php/issues/151
- [ ] https://github.com/opensearch-project/opensearch-go/issues/317
- [ ] https://github.com/opensearch-project/opensearch-net/issues/211

**Comment by dblock** [comment]
This is a dup of https://github.com/opensearch-project/opensearch-clients/issues/47.
