### ISSUE TITLE
[PROPOSAL] Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-clients#64]
### What are you proposing?

 Cleanup unused branches across client repos.

### What users have asked for this feature?

When we look at various vulnerability dashboards we look at 2.x branches. Most clients no longer ship anything out of 2.x.

### What problems are you trying to solve?

One have active branches to avoid people being worried about security vulnerabilities in inactive ones.

- [x] https://github.com/opensearch-project/opensearch-go/issues/547
- [x] https://github.com/opensearch-project/opensearch-java/issues/986
- [x] https://github.com/opensearch-project/opensearch-net/issues/645
- [x] https://github.com/opensearch-project/opensearch-php/issues/191
- [x] https://github.com/opensearch-project/opensearch-py/issues/744
- [x] https://github.com/opensearch-project/opensearch-ruby/issues/252
- [x] https://github.com/opensearch-project/opensearch-rs/issues/257
- [x] https://github.com/opensearch-project/opensearch-js/issues/775

**Comment by dblock** [comment]
Done for language clients.
