### ISSUE TITLE
Test and publish compatibility matrix with various OpenSearch versions

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-clients#8]
This is a meta issue for clients to add support to run integration tests across various versions of OpenSearch and publish a compatibility matrix for the client version vs OpenSearch version.

PR Reference: https://github.com/opensearch-project/opensearch-java/pull/122
Compatibility: https://github.com/opensearch-project/opensearch-java/blob/main/COMPATIBILITY.md

- [x] opensearch-js https://github.com/opensearch-project/opensearch-js/issues/214
- [x] opensearch-dsl-py: https://github.com/opensearch-project/opensearch-dsl-py/issues/42
- [x] opensearch-go: https://github.com/opensearch-project/opensearch-go/issues/97
- [x] opensearch-java: https://github.com/opensearch-project/opensearch-java/issues/128
- [x] opensearch-net: https://github.com/opensearch-project/opensearch-net/issues/26
- [x] opensearch-php: https://github.com/opensearch-project/opensearch-php/issues/47
- [x] opensearch-py: https://github.com/opensearch-project/opensearch-py/issues/144
- [x] opensearch-ruby: https://github.com/opensearch-project/opensearch-ruby/issues/56
- [x] opensearch-rs: https://github.com/opensearch-project/opensearch-rs/issues/37
